from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt


def _configure_document(document: Document) -> None:
    """Apply clear, professional formatting."""

    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    normal_style = document.styles["Normal"]
    normal_style.font.name = "Arial"
    normal_style.font.size = Pt(10.5)

    for style_name in ["Title", "Heading 1", "Heading 2"]:
        style = document.styles[style_name]
        style.font.name = "Arial"


def _add_bullet_list(
    document: Document,
    items: list[str],
    empty_message: str = "None detected",
) -> None:
    """Add a bullet list or a clear empty-state message."""

    if not items:
        document.add_paragraph(empty_message)
        return

    for item in items:
        paragraph = document.add_paragraph(
            style="List Bullet"
        )
        paragraph.add_run(str(item))


def _add_comparison_pair(
    document: Document,
    item: dict,
    heading: str,
) -> None:
    """Add one matched or partially matched requirement pair."""

    document.add_heading(
        heading,
        level=2,
    )

    table = document.add_table(
        rows=3,
        cols=2,
    )
    table.style = "Table Grid"

    rows = [
        (
            "Document A",
            item.get(
                "document_a_item",
                "Requires confirmation",
            ),
        ),
        (
            "Document B",
            item.get(
                "document_b_item",
                "Requires confirmation",
            ),
        ),
        (
            "Similarity",
            f"{item.get('similarity_score', 0):.0%}",
        ),
    ]

    for row, values in zip(table.rows, rows):
        label, value = values
        row.cells[0].text = label
        row.cells[1].text = str(value)
        row.cells[0].paragraphs[0].runs[0].bold = True

    review_note = item.get("review_note")

    if review_note:
        note = document.add_paragraph()
        note.add_run("Review note: ").bold = True
        note.add_run(str(review_note))


def create_comparison_word_report(
    comparison_result: dict,
) -> bytes:
    """
    Create a professional two-document comparison report.
    """

    document = Document()
    _configure_document(document)

    document_a_name = comparison_result.get(
        "document_a_name",
        "Document A",
    )
    document_b_name = comparison_result.get(
        "document_b_name",
        "Document B",
    )

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    title_run = title.add_run(
        "Preliminary Document Comparison Report"
    )
    title_run.bold = True
    title_run.font.name = "Arial"
    title_run.font.size = Pt(18)

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle_run = subtitle.add_run(
        "Generated by GovBA Assistant"
    )
    subtitle_run.italic = True
    subtitle_run.font.size = Pt(10)

    document.add_paragraph()

    source_table = document.add_table(
        rows=2,
        cols=2,
    )
    source_table.style = "Table Grid"

    source_items = [
        ("Document A", document_a_name),
        ("Document B", document_b_name),
    ]

    for row, values in zip(
        source_table.rows,
        source_items,
    ):
        label, value = values
        row.cells[0].text = label
        row.cells[1].text = str(value)
        row.cells[0].paragraphs[0].runs[0].bold = True

    notice = document.add_paragraph()
    notice_run = notice.add_run(
        "Important: This is a prototype comparison. "
        "It is not an official traceability, compliance, "
        "legal, or technical decision. A Business Analyst "
        "must verify every result."
    )
    notice_run.bold = True

    document.add_heading(
        "1. Comparison Summary",
        level=1,
    )

    summary = comparison_result.get(
        "summary",
        {},
    )

    summary_table = document.add_table(
        rows=7,
        cols=2,
    )
    summary_table.style = "Table Grid"

    summary_items = [
        (
            "Comparison Mode",
            comparison_result.get(
                "comparison_mode",
                "Requires confirmation",
            ),
        ),
        (
            "Coverage Indicator",
            f"{comparison_result.get('coverage_indicator', 0)}%",
        ),
        (
            "Matched Items",
            summary.get("matched_count", 0),
        ),
        (
            "Partial Matches",
            summary.get("partial_match_count", 0),
        ),
        (
            f"Missing from {document_b_name}",
            summary.get("missing_count", 0),
        ),
        (
            f"Additional in {document_b_name}",
            summary.get("additional_count", 0),
        ),
        (
            "Possible Conflicts",
            summary.get("possible_conflict_count", 0),
        ),
    ]

    for row, values in zip(
        summary_table.rows,
        summary_items,
    ):
        label, value = values
        row.cells[0].text = str(label)
        row.cells[1].text = str(value)
        row.cells[0].paragraphs[0].runs[0].bold = True

    document.add_heading(
        "2. Matched Items",
        level=1,
    )

    matched_items = comparison_result.get(
        "matched_items",
        [],
    )

    if matched_items:
        for index, item in enumerate(
            matched_items,
            start=1,
        ):
            _add_comparison_pair(
                document,
                item,
                f"Match {index}",
            )
    else:
        document.add_paragraph(
            "No full matches were detected."
        )

    document.add_heading(
        "3. Partial Matches",
        level=1,
    )

    partial_matches = comparison_result.get(
        "partial_matches",
        [],
    )

    if partial_matches:
        for index, item in enumerate(
            partial_matches,
            start=1,
        ):
            _add_comparison_pair(
                document,
                item,
                f"Partial Match {index}",
            )
    else:
        document.add_paragraph(
            "No partial matches were detected."
        )

    document.add_heading(
        f"4. Missing from {document_b_name}",
        level=1,
    )

    _add_bullet_list(
        document,
        comparison_result.get(
            "missing_in_document_b",
            [],
        ),
    )

    document.add_heading(
        f"5. Additional in {document_b_name}",
        level=1,
    )

    _add_bullet_list(
        document,
        comparison_result.get(
            "additional_in_document_b",
            [],
        ),
    )

    document.add_heading(
        "6. Possible Conflicts",
        level=1,
    )

    conflicts = comparison_result.get(
        "possible_conflicts",
        [],
    )

    if conflicts:
        for index, conflict in enumerate(
            conflicts,
            start=1,
        ):
            document.add_heading(
                f"Possible Conflict {index}",
                level=2,
            )

            conflict_table = document.add_table(
                rows=4,
                cols=2,
            )
            conflict_table.style = "Table Grid"

            conflict_items = [
                (
                    "Document A",
                    conflict.get(
                        "document_a_item",
                        "Requires confirmation",
                    ),
                ),
                (
                    "Document B",
                    conflict.get(
                        "document_b_item",
                        "Requires confirmation",
                    ),
                ),
                (
                    "Reason",
                    conflict.get(
                        "reason",
                        "Requires confirmation",
                    ),
                ),
                (
                    "Similarity",
                    f"{conflict.get('similarity_score', 0):.0%}",
                ),
            ]

            for row, values in zip(
                conflict_table.rows,
                conflict_items,
            ):
                label, value = values
                row.cells[0].text = str(label)
                row.cells[1].text = str(value)
                row.cells[0].paragraphs[0].runs[0].bold = True
    else:
        document.add_paragraph(
            "No numerical conflicts were detected."
        )

    document.add_heading(
        "7. Human Review Notes",
        level=1,
    )

    _add_bullet_list(
        document,
        comparison_result.get(
            "human_review_notes",
            [],
        ),
    )

    document.add_paragraph()

    footer_note = document.add_paragraph()
    footer_note.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_run = footer_note.add_run(
        "GovBA Assistant — Internship Prototype"
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    output = BytesIO()
    document.save(output)

    return output.getvalue()