from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt


def _configure_document(document: Document) -> None:
    """Apply simple professional formatting to the review report."""

    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    normal_style = document.styles["Normal"]
    normal_style.font.name = "Arial"
    normal_style.font.size = Pt(10.5)

    for style_name in ["Title", "Heading 1", "Heading 2"]:
        style = document.styles[style_name]
        style.font.name = "Arial"


def _add_bullet_list(
    document: Document,
    items: list[str],
) -> None:
    """Add bullet items to the Word report."""

    valid_items = items or ["None detected"]

    for item in valid_items:
        paragraph = document.add_paragraph(
            style="List Bullet"
        )
        paragraph.add_run(str(item))


def create_review_word_report(
    review_result: dict,
    source_name: str,
) -> bytes:
    """
    Create a professional BRD/SRS review report in Word format.
    """

    document = Document()
    _configure_document(document)

    document_type = review_result.get(
        "document_type",
        "Requirements Document",
    )

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    title_run = title.add_run(
        f"Preliminary {document_type} Review Report"
    )
    title_run.bold = True
    title_run.font.name = "Arial"
    title_run.font.size = Pt(18)

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle_run = subtitle.add_run(
        "Generated by GovBA Assistant"
    )
    subtitle_run.italic = True
    subtitle_run.font.size = Pt(10)

    document.add_paragraph()

    document.add_paragraph(
        f"Source: {source_name}"
    )

    notice = document.add_paragraph()
    notice_run = notice.add_run(
        "Important: This is a prototype review. "
        "It is not an official Ministry compliance score. "
        "A Business Analyst must verify every finding."
    )
    notice_run.bold = True

    document.add_heading(
        "1. Review Summary",
        level=1,
    )

    summary_table = document.add_table(
        rows=4,
        cols=2,
    )
    summary_table.style = "Table Grid"

    summary_items = [
        (
            "Document Type",
            review_result.get(
                "document_type",
                "Requires confirmation",
            ),
        ),
        (
            "Review Mode",
            review_result.get(
                "review_mode",
                "Requires confirmation",
            ),
        ),
        (
            "Completeness Indicator",
            f"{review_result.get('completeness_indicator', 0)}%",
        ),
        (
            "Missing or Unclear Sections",
            str(
                len(
                    review_result.get(
                        "missing_sections",
                        [],
                    )
                )
            ),
        ),
    ]

    for row, values in zip(
        summary_table.rows,
        summary_items,
    ):
        label, value = values

        row.cells[0].text = label
        row.cells[1].text = str(value)
        row.cells[0].paragraphs[0].runs[0].bold = True

    document.add_heading(
        "2. Section Checklist",
        level=1,
    )

    checklist = review_result.get(
        "section_checklist",
        [],
    )

    checklist_table = document.add_table(
        rows=1,
        cols=3,
    )
    checklist_table.style = "Table Grid"

    header_cells = checklist_table.rows[0].cells
    header_cells[0].text = "Section"
    header_cells[1].text = "Status"
    header_cells[2].text = "Evidence"

    for cell in header_cells:
        cell.paragraphs[0].runs[0].bold = True

    for item in checklist:
        row_cells = checklist_table.add_row().cells

        evidence = item.get(
            "evidence",
            [],
        )

        row_cells[0].text = str(
            item.get("section", "")
        )
        row_cells[1].text = str(
            item.get("status", "")
        )
        row_cells[2].text = (
            ", ".join(evidence)
            if evidence
            else "No clear evidence detected"
        )

    document.add_heading(
        "3. Detected Sections",
        level=1,
    )

    _add_bullet_list(
        document,
        review_result.get(
            "detected_sections",
            [],
        ),
    )

    document.add_heading(
        "4. Missing or Unclear Sections",
        level=1,
    )

    _add_bullet_list(
        document,
        review_result.get(
            "missing_sections",
            [],
        ),
    )

    document.add_heading(
        "5. Wording Issues",
        level=1,
    )

    _add_bullet_list(
        document,
        review_result.get(
            "wording_issues",
            [],
        ),
    )

    document.add_heading(
        "6. Recommendations",
        level=1,
    )

    _add_bullet_list(
        document,
        review_result.get(
            "recommendations",
            [],
        ),
    )

    document.add_heading(
        "7. Human Review Notes",
        level=1,
    )

    _add_bullet_list(
        document,
        review_result.get(
            "human_review_notes",
            [],
        ),
    )

    document.add_paragraph()

    footer_note = document.add_paragraph()
    footer_note.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_run = footer_note.add_run(
        "GovBA Assistant — Internship Prototype"
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    output = BytesIO()
    document.save(output)

    return output.getvalue()