from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt


def _add_bullet_list(
    document: Document,
    items: list[str],
) -> None:
    """Add a list of items to the Word document."""

    valid_items = items or ["Requires confirmation"]

    for item in valid_items:
        paragraph = document.add_paragraph(
            style="List Bullet"
        )
        paragraph.add_run(str(item))


def _configure_document(document: Document) -> None:
    """Apply simple professional formatting."""

    section = document.sections[0]

    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    normal_style = document.styles["Normal"]
    normal_style.font.name = "Arial"
    normal_style.font.size = Pt(10.5)

    for style_name in [
        "Title",
        "Heading 1",
        "Heading 2",
    ]:
        style = document.styles[style_name]
        style.font.name = "Arial"


def create_brd_word_report(
    result: dict,
    source_name: str,
) -> bytes:
    """
    Create a professional preliminary BRD Word report.

    Parameters
    ----------
    result:
        Structured BRD result created by the analysis engine.

    source_name:
        Name of the uploaded document or manual input source.

    Returns
    -------
    bytes
        The completed DOCX file as bytes.
    """

    document = Document()
    _configure_document(document)

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    title_run = title.add_run(
        "Preliminary Business Requirements Document"
    )

    title_run.bold = True
    title_run.font.name = "Arial"
    title_run.font.size = Pt(18)

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle_run = subtitle.add_run(
        "Generated by GovBA Assistant"
    )

    subtitle_run.italic = True
    subtitle_run.font.size = Pt(10)

    document.add_paragraph()

    document.add_paragraph(
        f"Source: {source_name}"
    )

    notice = document.add_paragraph()

    notice_run = notice.add_run(
        "Important: This is a preliminary draft. "
        "A Business Analyst must review, correct, "
        "and approve all content before use."
    )

    notice_run.bold = True

    overview = result.get(
        "service_overview",
        {},
    )

    document.add_heading(
        "1. Service Overview",
        level=1,
    )

    overview_table = document.add_table(
        rows=3,
        cols=2,
    )

    overview_table.style = "Table Grid"

    overview_items = [
        (
            "Service Name",
            overview.get(
                "service_name",
                "Requires confirmation",
            ),
        ),
        (
            "Service Purpose",
            overview.get(
                "service_purpose",
                "Requires confirmation",
            ),
        ),
        (
            "Service Scope",
            overview.get(
                "service_scope",
                "Requires confirmation",
            ),
        ),
    ]

    for row, values in zip(
        overview_table.rows,
        overview_items,
    ):
        label, value = values

        row.cells[0].text = label
        row.cells[1].text = str(value)

        row.cells[0].paragraphs[0].runs[0].bold = True

    document.add_heading(
        "2. Stakeholders",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get("stakeholders", []),
    )

    document.add_heading(
        "3. Service Recipients",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get("service_recipients", []),
    )

    document.add_heading(
        "4. Functional Requirements",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get(
            "functional_requirements",
            [],
        ),
    )

    document.add_heading(
        "5. Non-Functional Requirements",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get(
            "non_functional_requirements",
            [],
        ),
    )

    document.add_heading(
        "6. Business Rules",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get("business_rules", []),
    )

    document.add_heading(
        "7. Process Steps",
        level=1,
    )

    process_steps = result.get(
        "process_steps",
        [],
    )

    if process_steps:
        for number, step in enumerate(
            process_steps,
            start=1,
        ):
            paragraph = document.add_paragraph()
            paragraph.add_run(
                f"{number}. {step}"
            )

    else:
        document.add_paragraph(
            "Requires confirmation"
        )

    document.add_heading(
        "8. Required Data and Documents",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get(
            "required_data_and_documents",
            [],
        ),
    )

    document.add_heading(
        "9. Integration Requirements",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get(
            "integration_requirements",
            [],
        ),
    )

    document.add_heading(
        "10. Missing Information",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get(
            "missing_information",
            [],
        ),
    )

    document.add_heading(
        "11. Human Review Notes",
        level=1,
    )

    _add_bullet_list(
        document,
        result.get(
            "human_review_notes",
            [],
        ),
    )

    document.add_paragraph()

    footer_note = document.add_paragraph()
    footer_note.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_run = footer_note.add_run(
        "GovBA Assistant — Internship Prototype"
    )

    footer_run.italic = True
    footer_run.font.size = Pt(9)

    output = BytesIO()
    document.save(output)

    return output.getvalue()